services:
  discord:
    build:
      context: .
      dockerfile: discord/Dockerfile
    volumes:
      - ./discord:/app
    env_file:
      - ./envs/discord.env
      - ./envs/sentry.env
    restart: always
